### PR TITLE
fix: editor.selectionBackground

### PR DESCRIPTION
**Pull request by bufan-huang**
Under the dark theme, highlight more prominently when selected
b:
前
a:
后

### CODE REVIEW

**Review by Wxh16144 — APPROVED** [review]

**Comment by saturnonearth** [comment]
Awesome!!! Does this also affect auto-complete?

CleanShot 2023-11-15 at 02 28 01@2x

The first option in this example is selected but barely visible to me.

**Comment by bufan-huang** [comment]
> Awesome!!! Does this also affect auto-complete?
> 
> CleanShot 2023-11-15 at 02 28 01@2x
> 
> The first option in this example is selected but barely visible to me.

image
get

**Review by antfu — CHANGES_REQUESTED** [review]
Those files are generated, please edit the source files otherwise they will be overriden

**Comment by bufan-huang** [comment]
> Those files are generated, please edit the source files otherwise they will be overriden
OK 
image

**Comment by antfu** [comment]
Thanks! Tho I am not a fan of colored selection color, I have increased the contrast a bit, feel free to bring it back if it's still not enough

**Pull request closed without merging**
